# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'Contacts' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Contacts
	pod 'YYCache'
	pod 'FMDB'
	pod 'MJExtension'

end
